### ISSUE TITLE
MLAG not working after successful deployment

### ISSUE THREAD

**Issue by kenkitts** [CumulusNetworks/cldemo-config-mlag#12]
Despite working through the initial issue of the deployment.yaml not referencing the host file properly, which is being targeted by a pull request as I write this, the MLAG configuration does not work after deployment.  The packets from the server are ARPing for the next hop address on one of the available uplinks, but get no response from the leaf switches.

I will do more research and try to figure out what is not configured properly, though my knowledge in this space is limited.

**Comment by ericpulvino** [comment]
I know what this issue is...
This is an issue I've been dealing with for years. The virtio version in older ubuntus did not carry our upstream kernel patch to allow the virtio driver to report speed/duplex. The fix is to force older ubuntus to use e1000 driver (we do this part already) and to also set the speed/duplex for that driver manually ( it does not have a default value like our virtio patch provides)

**Comment by ericpulvino** [comment]
Should be fixed now! Feel free to ping me if not.

**Comment by adam-fulford** [comment]
![image](https://user-images.githubusercontent.com/51921931/59688578-ff4a3800-91ab-11e9-9470-48e540bc1724.png)

I am having issues with the ping after executing the demo.

**Comment by adam-fulford** [comment]
![image](https://user-images.githubusercontent.com/51921931/59688703-3fa9b600-91ac-11e9-863b-eae4a53f6a56.png)

It looks like the "peer interface" is missing?
